version: "3.7"
services:
  jupyterlab:
    user: root
    build:
      context: ./jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - "./work:/home/jovyan/work:cached"
    environment:
      TZ: "Asia/Tokyo"
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
